/**
 * THΛNAL (തണൽ) — DATA STORE
 * Centralized data provider with embedded data for offline/file-protocol compatibility.
 */

window.ThanalData = {
  districts: [
    {
      id: "kasaragod",
      name: "Kasaragod",
      nameMl: "കാസർഗോഡ്",
      tagline: "The Northern Citadel of Seven Tongues",
      description: "Perched at Kerala's northern frontier, Kasaragod is a tranquil tapestry of majestic coastal forts, winding backwaters, coir-making hamlets, and rich multi-lingual heritage.",
      image: "assets/images/districts/kasaragod.png",
      region: "North Kerala (Malabar)",
      bestSeason: "October to March",
      idealDays: "2 - 3 Days",
      topDestinations: ["Bekal Fort", "Chandragiri Fort", "Ranipuram Hills", "Valiyaparamba Backwaters"],
      keyExperiences: ["Sunset on Bekal ramparts", "Cruising Valiyaparamba backwaters", "Ranipuram shola trekking", "Witnessing rare Theyyam rituals"],
      foodSpecialties: ["Malabar Biryani", "Pathiri with fish curry", "Kallummakkaya"],
      pageUrl: "pages/districts/kasaragod.html"
    },
    {
      id: "kannur",
      name: "Kannur",
      nameMl: "കണ്ണൂർ",
      tagline: "The Realm of Looms, Lore & Living Gods",
      description: "Kannur pulses with ancient energy: from the mesmerizing sacred dance of Theyyam to Asia's longest drive-in beach at Muzhappilangad, colonial sea forts, and handloom traditions.",
      image: "assets/images/districts/kannur.png",
      region: "North Kerala (Malabar)",
      bestSeason: "November to February",
      idealDays: "2 - 3 Days",
      topDestinations: ["Muzhappilangad Drive-in Beach", "St. Angelo Fort", "Dharmadam Island", "Paithalmala Peak"],
      keyExperiences: ["Night-long Theyyam ceremonies", "Driving along Muzhappilangad sands", "Exploring St. Angelo Fort", "Hiking Paithalmala ridge"],
      foodSpecialties: ["Thalassery Biryani", "Arikadukka", "Unnakaya"],
      pageUrl: "pages/districts/kannur.html"
    },
    {
      id: "wayanad",
      name: "Wayanad",
      nameMl: "വയനാട്",
      tagline: "Misty Highlands & Prehistoric Echoes",
      description: "High on the Western Ghats plateau, Wayanad is an emerald paradise of cardamom plantations, bamboo forests, Neolithic cave petroglyphs, and untamed elephant corridors.",
      image: "assets/images/districts/wayanad.png",
      region: "North Kerala (Western Ghats)",
      bestSeason: "September to May",
      idealDays: "3 - 4 Days",
      topDestinations: ["Chembra Peak", "Edakkal Caves", "Banasura Sagar Dam", "Kuruva Island"],
      keyExperiences: ["Edakkal prehistoric cave petroglyphs", "Trek to Chembra heart lake", "Bamboo rafting at Kuruva Dweep", "Muthanga wildlife safari"],
      foodSpecialties: ["Gandhakasala rice dishes", "Bamboo shoot curry", "Wild forest honey"],
      pageUrl: "pages/districts/wayanad.html"
    },
    {
      id: "kozhikode",
      name: "Kozhikode",
      nameMl: "കോഴിക്കോട്",
      tagline: "The Capital of Spices & Malabar Soul",
      description: "The historic port where spice trade forged legendary culinary artistry, literary intellect, warm hospitality, and historic shoreline piers.",
      image: "assets/images/districts/kozhikode.png",
      region: "North Kerala (Malabar)",
      bestSeason: "October to March",
      idealDays: "2 - 3 Days",
      topDestinations: ["Kozhikode Beach Pier", "SM Street", "Kappad Beach", "Beypore Shipbuilding Yard"],
      keyExperiences: ["Sampling authentic Halwa and Dum Biryani", "Handmade Uru ships at Beypore", "Sunset past colonial pier ruins", "Thusharagiri waterfall trek"],
      foodSpecialties: ["Kozhikodan Biryani", "Calicut Halwa", "Sulaimani Tea"],
      pageUrl: "pages/districts/kozhikode.html"
    },
    {
      id: "malappuram",
      name: "Malappuram",
      nameMl: "മലപ്പുറം",
      tagline: "Hill Terraces, Royal Teak & Cultural Heritage",
      description: "Framed by the Arabian Sea and Nilgiri foothills, Malappuram is renowned for the world's oldest teak plantation at Nilambur, sacred pilgrimage centres, and football passion.",
      image: "assets/images/districts/malappuram.png",
      region: "North-Central Kerala",
      bestSeason: "September to March",
      idealDays: "2 Days",
      topDestinations: ["Nilambur Teak Museum", "Kottakkal Arya Vaidya Sala", "Nedumkayam Rainforest", "Padinharekara Beach"],
      keyExperiences: ["Walking through oldest teak plantation", "Traditional Ayurveda treatments", "Watching Sevens football match", "Birdwatching at river estuary"],
      foodSpecialties: ["Erachi Puttu", "Ada Pradhaman", "Malabar Mutton Curry"],
      pageUrl: "pages/districts/malappuram.html"
    },
    {
      id: "palakkad",
      name: "Palakkad",
      nameMl: "പാലക്കാട്",
      tagline: "The Mountain Pass & Verdant Rice Fields",
      description: "Guarding Kerala's primary mountain corridor through the Western Ghats, Palakkad is the state's rice bowl with granite forts and untouched rainforests.",
      image: "assets/images/districts/palakkad.png",
      region: "Central Kerala",
      bestSeason: "November to February",
      idealDays: "2 - 3 Days",
      topDestinations: ["Palakkad Fort", "Silent Valley National Park", "Malampuzha Dam", "Nelliyampathy Hills"],
      keyExperiences: ["Primeval quiet of Silent Valley", "Granite ramparts of Tipu's Fort", "Nelliyampathy orange orchard drive", "Kalpathy heritage village walk"],
      foodSpecialties: ["Palakkadan Matta Rice", "Ramaswamy Idli", "Jackfruit Elayappam"],
      pageUrl: "pages/districts/palakkad.html"
    },
    {
      id: "thrissur",
      name: "Thrissur",
      nameMl: "തൃശ്ശൂർ",
      tagline: "The Cultural Crucible of Kerala",
      description: "Built spirally around a hillock crowned by Vadakkumnathan temple, Thrissur is Kerala's cultural heart, celebrated globally for Thrissur Pooram.",
      image: "assets/images/districts/thrissur.png",
      region: "Central Kerala",
      bestSeason: "October to April",
      idealDays: "2 - 3 Days",
      topDestinations: ["Vadakkumnathan Temple", "Athirappilly & Vazhachal Waterfalls", "Kerala Kalamandalam", "Chavakkad Beach"],
      keyExperiences: ["Standing before Niagara of India at Athirappilly", "Classical Kathakali at Kalamandalam", "Thunderous Ilanjithara Melam percussion", "Chavakkad estuary sunset"],
      foodSpecialties: ["Thrissur Vellayappam", "Meen Peera", "Roast Duck Curry"],
      pageUrl: "pages/districts/thrissur.html"
    },
    {
      id: "ernakulam",
      name: "Ernakulam",
      nameMl: "എറണാകുളം",
      tagline: "The Commercial Hub & Colonial Harbor of Kochi",
      description: "Where modern cosmopolitan flair meets spice warehouses, Chinese fishing nets, 500-year-old Portuguese synagogues, and vibrant island ferries.",
      image: "assets/images/districts/ernakulam.png",
      region: "Central Kerala",
      bestSeason: "October to March",
      idealDays: "3 - 4 Days",
      topDestinations: ["Fort Kochi & Chinese Nets", "Mattancherry & Jew Town", "Marine Drive", "Kadamakudy Islands"],
      keyExperiences: ["Bicycle ride through Fort Kochi lanes", "Ferry past cantilevered Chinese nets", "Kayaking through Kadamakudy prawn farms", "Contemporary art biennale galleries"],
      foodSpecialties: ["Cochin Seafood Platter", "Appam with mutton stew", "Fish Molly"],
      pageUrl: "pages/districts/ernakulam.html"
    },
    {
      id: "idukki",
      name: "Idukki",
      nameMl: "ഇടുക്കി",
      tagline: "The Highland Kingdom of Mist & Spices",
      description: "Dominated by towering peaks of the Western Ghats, sprawling tea gardens, wildlife sanctuaries, and Asia's first arch dam.",
      image: "assets/images/districts/idukki.png",
      region: "Highland Kerala",
      bestSeason: "September to May",
      idealDays: "3 - 5 Days",
      topDestinations: ["Munnar Tea Estates", "Eravikulam National Park", "Idukki Arch Dam", "Vagamon Meadows"],
      keyExperiences: ["Carpeted green tea slopes of Munnar", "Spotting Nilgiri Tahr on Anamudi slopes", "Bamboo rafting in Periyar Reserve", "Paragliding over Vagamon hills"],
      foodSpecialties: ["Fresh Cardamom Tea", "Tapioca with Kanthari Fish Curry", "Highland Duck Roast"],
      pageUrl: "pages/districts/idukki.html"
    },
    {
      id: "kottayam",
      name: "Kottayam",
      nameMl: "കോട്ടയം",
      tagline: "The Land of Letters, Lakes & Rubber Groves",
      description: "Nestled between the Western Ghats and Vembanad Lake, Kottayam is the hub of publishing, Syrian Christian cuisine, rubber plantations, and backwaters.",
      image: "assets/images/districts/kottayam.png",
      region: "South-Central Kerala",
      bestSeason: "September to March",
      idealDays: "2 - 3 Days",
      topDestinations: ["Kumarakom Bird Sanctuary", "Vembanad Lake", "Illikkal Kallu Peak", "Aymanam Village"],
      keyExperiences: ["Birdwatching at Kumarakom sanctuary", "Silent canoeing through Aymanam waterways", "Hike to knife-edge cliff at Illikkal Kallu", "Syrian Christian duck roast feast"],
      foodSpecialties: ["Karimeen Pollichathu", "Syrian Beef Fry & Porotta", "Appam with Duck Roast"],
      pageUrl: "pages/districts/kottayam.html"
    },
    {
      id: "alappuzha",
      name: "Alappuzha",
      nameMl: "ആലപ്പുഴ",
      tagline: "The Venice of the East & Backwater Capital",
      description: "An intricate maze of shimmering canals, endless paddy fields cultivated below sea level in Kuttanad, thatched houseboats, and coir weaving.",
      image: "assets/images/districts/alappuzha.png",
      region: "South Kerala",
      bestSeason: "September to March",
      idealDays: "2 - 3 Days",
      topDestinations: ["Alappuzha Backwater Canals", "Kuttanad Polders", "Marari Beach", "Alappuzha Lighthouse"],
      keyExperiences: ["Overnight cruise on a luxury eco-kettuvallam", "Silent country canoe through village canals", "Roaring Nehru Trophy Snake Boat Race", "Unwinding on Marari white sands"],
      foodSpecialties: ["Fresh Pearl Spot (Karimeen) Fry", "Kuttanadan Duck Mappas", "Toddy Shop Fish Curry"],
      pageUrl: "pages/districts/alappuzha.html"
    },
    {
      id: "pathanamthitta",
      name: "Pathanamthitta",
      nameMl: "പത്തനംതിട്ട",
      tagline: "The Pilgrim Capital & Sacred Forest Hills",
      description: "The spiritual heartland of Kerala, bordered by dense forest reserves, sacred hill temples, the mirror craft of Aranmula, and holy rivers.",
      image: "assets/images/districts/pathanamthitta.png",
      region: "South Kerala",
      bestSeason: "September to February",
      idealDays: "2 Days",
      topDestinations: ["Sabarimala Shrine", "Aranmula Heritage Village", "Gavi Eco-Reserve", "Konni Elephant Reserve"],
      keyExperiences: ["Witnessing metal casting of Aranmula Kannadi mirrors", "Deep forest safari at misty Gavi", "Timber elephants at Konni training kraal", "Aranmula Valla Sadya feast"],
      foodSpecialties: ["Aranmula Valla Sadya", "Unniyappam", "Palada Pradhaman"],
      pageUrl: "pages/districts/pathanamthitta.html"
    },
    {
      id: "kollam",
      name: "Kollam",
      nameMl: "കൊല്ലം",
      tagline: "The Cashew Capital & Gateway to Ashtamudi",
      description: "An ancient international seaport on the shores of eight-armed Ashtamudi Lake, known for cashew processing, Tangasseri lighthouse, and coastal boat cruises.",
      image: "assets/images/districts/kollam.png",
      region: "South Kerala",
      bestSeason: "October to March",
      idealDays: "2 - 3 Days",
      topDestinations: ["Ashtamudi Lake & Munroe Island", "Jatayu Earth's Center", "Tangasseri Lighthouse", "Shendurney Sanctuary"],
      keyExperiences: ["Canoe through mangrove waterways of Munroe Island", "Cable car to giant Jatayu sculpture", "Climbing Tangasseri lighthouse for ocean views", "DTPC boat cruise to Alappuzha"],
      foodSpecialties: ["Kollam style Fish Curry", "Roasted Cashew delights", "Tapioca with sardine gravy"],
      pageUrl: "pages/districts/kollam.html"
    },
    {
      id: "thiruvananthapuram",
      name: "Thiruvananthapuram",
      nameMl: "തിരുവനന്തപുരം",
      tagline: "The Regal Capital of Cliffs, Cove & Castles",
      description: "The stately capital city where the wealth and sanctity of Sree Padmanabhaswamy Temple blend with the dramatic red laterite cliffs of Varkala and Kovalam.",
      image: "assets/images/districts/thiruvananthapuram.png",
      region: "South Kerala",
      bestSeason: "September to March",
      idealDays: "3 - 4 Days",
      topDestinations: ["Padmanabhaswamy Temple", "Varkala Cliff Beach", "Kovalam Lighthouse Beach", "Ponmudi Hills"],
      keyExperiences: ["Dramatic Arabian sunsets from Varkala cliff cafes", "Dravidian stone architecture of Padmanabhaswamy", "Morning drive through 22 hairpin bends of Ponmudi", "Ayurvedic rejuvenating massage in Kovalam"],
      foodSpecialties: ["Trivandrum Style Sadya", "Boli & Payasam", "Kothu Porotta"],
      pageUrl: "pages/districts/thiruvananthapuram.html"
    }
  ]
};
